### ISSUE TITLE
I feel 0 unlimited stuff :D

### ISSUE THREAD

**Issue by iceman-twitch** [Dogeyy/unlimited-ammo#2]
I have copied your addon amazing if it works :D
But it is actually do nothing with hl2 weapons.
My ulx 3.62 and ulib 2.52

**Comment by iceman-twitch** [comment]
Solved now and added ar2 ammo :D because it was missing :D

**Comment by Dogeyy** [comment]
You could always make a pull request, and I'd merge it :)

**Comment by iceman-twitch** [comment]
Okay :D
